import * as esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import builtins from 'builtin-modules';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const prod = process.argv.includes('--production');

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

if (!Map.prototype.getOrInsertComputed) {
    Map.prototype.getOrInsertComputed = function(key, computeFn) {
        if (this.has(key)) return this.get(key);
        var value = computeFn();
        this.set(key, value);
        return value;
    };
}
`;

/**
 * Extract the foliate-js commit ref from bun.lock.
 * Falls back to 'main' if the lockfile can't be parsed.
 */
function getFoliateRef(): string {
  // bun.lock uses trailing commas (not strict JSON), so use regex instead of JSON.parse
  const lockContent = fs.readFileSync(path.resolve(__dirname, 'bun.lock'), 'utf8');
  const match = lockContent.match(/"foliate-js@github:[^"]+#([a-f0-9]+)"/);
  return match?.[1] ?? 'main';
}

/**
 * Prepare the foliate-js PDF resources (worker, CSS) to be inlined at build time.
 * Equivalent to the prepareFoliatePdf() Vite plugin.
 */
function prepareFoliateResources() {
  const pdfDir = path.resolve(__dirname, 'node_modules/foliate-js/vendor/pdfjs');
  const workerCode = fs.readFileSync(path.join(pdfDir, 'pdf.worker.mjs'), 'utf8');
  const workerCodeBase64 = Buffer.from(workerCode).toString('base64');
  const textLayerBuilderCSS = fs.readFileSync(
    path.join(pdfDir, 'text_layer_builder.css'),
    'utf8',
  );
  const annotationLayerBuilderCSS = fs.readFileSync(
    path.join(pdfDir, 'annotation_layer_builder.css'),
    'utf8',
  );
  const foliateRef = getFoliateRef();
  const pdfAssetBase = `https://cdn.jsdelivr.net/gh/johnfactotum/foliate-js@${foliateRef}/vendor/pdfjs/`;

  return { workerCodeBase64, textLayerBuilderCSS, annotationLayerBuilderCSS, pdfAssetBase };
}

/**
 * esbuild plugin: transform foliate-js/pdf.js to inline the PDF.js worker and CSS.
 * Replicates the prepareFoliatePdf Vite plugin behavior.
 */
function foliatePdfPlugin(): esbuild.Plugin {
  const res = prepareFoliateResources();

  return {
    name: 'foliate-pdf',
    setup(build) {
      // Intercept foliate-js/pdf.js and transform its source
      build.onLoad(
        { filter: /node_modules\/foliate-js\/pdf\.js$/ },
        async (args) => {
          let code = await fs.promises.readFile(args.path, 'utf8');

          // Replace dynamic URL-based path resolution with static inlined resources
          code = code.replace(
            "const pdfjsPath = path => new URL(`vendor/pdfjs/${path}`, import.meta.url).toString()",
            `const pdfjsWorkerCode = atob(${JSON.stringify(res.workerCodeBase64)})\nconst pdfjsWorkerUrl = URL.createObjectURL(new Blob([pdfjsWorkerCode], { type: 'text/javascript' }))\nconst pdfjsPath = path => path === 'pdf.worker.mjs'\n    ? pdfjsWorkerUrl\n    : path === 'cmaps/'\n        ? '${res.pdfAssetBase}cmaps/'\n        : path === 'standard_fonts/'\n            ? '${res.pdfAssetBase}standard_fonts/'\n            : path`,
          );

          // Replace dynamic fetchText() calls for CSS with inlined CSS strings
          code = code.replace(
            /const fetchText = async url => await \(await fetch\(url\)\)\.text\(\)\n\n\/\/ https:\/\/raw\.githubusercontent\.com\/mozilla\/pdf\.js\/refs\/tags\/v5\.5\.207\/web\/text_layer_builder\.css\nconst textLayerBuilderCSS = await fetchText\(pdfjsPath\('text_layer_builder\.css'\)\)\n\n\/\/ https:\/\/raw\.githubusercontent\.com\/mozilla\/pdf\.js\/refs\/tags\/v5\.5\.207\/web\/annotation_layer_builder\.css\nconst annotationLayerBuilderCSS = await fetchText\(pdfjsPath\('annotation_layer_builder\.css'\)\)/,
            `const textLayerBuilderCSS = ${JSON.stringify(res.textLayerBuilderCSS)}\nconst annotationLayerBuilderCSS = ${JSON.stringify(res.annotationLayerBuilderCSS)}`,
          );

          return { contents: code, loader: 'js' };
        },
      );
    },
  };
}

/**
 * esbuild plugin: ignore CSS imports from dependencies.
 * Replicates the ignoreCSS Vite plugin behavior.
 */
function ignoreCssPlugin(): esbuild.Plugin {
  return {
    name: 'ignore-css',
    setup(build) {
      // Return empty content for all .css files
      build.onLoad({ filter: /\.css$/ }, () => ({
        contents: '',
        loader: 'css',
      }));

      // Mark .css imports as side-effect-free so they're tree-shaken
      build.onResolve({ filter: /\.css$/ }, (args) => ({
        path: args.path,
        namespace: 'ignore-css',
        sideEffects: false,
      }));
    },
  };
}

/**
 * Build the standalone styles.css from src/global.css.
 * Obsidian loads styles.css from the plugin root, not via JS import.
 */
async function buildStyles(): Promise<void> {
  const css = await fs.promises.readFile('src/global.css', 'utf8');

  const outputCss = prod
    ? (await esbuild.transform(css, { loader: 'css', minify: true })).code
    : css;

  await fs.promises.writeFile('styles.css', outputCss);
  console.log('Written styles.css');
}

const buildConfig: esbuild.BuildOptions = {
  entryPoints: [path.resolve(__dirname, 'src/main.ts')],
  bundle: true,
  outfile: 'main.js',
  format: 'cjs',
  platform: 'node',
  target: 'es2021',
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  banner: { js: banner },
  minify: prod,
  sourcemap: prod ? false : 'inline',
  define: {
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  },
  plugins: [foliatePdfPlugin(), ignoreCssPlugin()],
  // Suppress esbuild warnings about dynamic import — foliate-js uses them
  // but we inline dynamic imports via esbuild's default behavior
  logLevel: 'info',
};

async function main() {
  if (prod) {
    // Production: one-shot build + styles
    console.log('Building for production...');
    await esbuild.build(buildConfig);
    await buildStyles();
    console.log('Build complete.');
  } else {
    // Development: watch mode + styles
    console.log('Building for development (watch mode)...');

    await buildStyles();

    const ctx = await esbuild.context(buildConfig);
    await ctx.watch();
    console.log('Watching for changes...');
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
