import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import postcss from "postcss";
import tailwindcss from "@tailwindcss/postcss";
import fs from "fs";
import path from "path";
import { createRequire } from "module";

const require = createRequire(import.meta.url);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

// Polyfill for pdfjs-dist v5 which uses Map.prototype.getOrInsertComputed
if (!Map.prototype.getOrInsertComputed) {
    Map.prototype.getOrInsertComputed = function(key, computeFn) {
        if (this.has(key)) return this.get(key);
        var value = computeFn();
        this.set(key, value);
        return value;
    };
}
`;

const prod = (process.argv[2] === "production");
const cssSource = "src/global.css";
const cssOutput = "styles.css";

async function buildStyles() {
  const css = await fs.promises.readFile(cssSource, "utf8");
  const allCss = css;

  const result = await postcss([
    tailwindcss,
  ]).process(allCss, { from: cssSource, to: cssOutput });

  const outputCss = prod
    ? (await esbuild.transform(result.css, {loader: "css", minify: true})).code
    : result.css;

  await fs.promises.writeFile(cssOutput, outputCss);
  console.log(`Written ${cssOutput}`);
}

// Read assets for PDF book adapter defines
const workerPath = require.resolve('pdfjs-dist/build/pdf.worker.min.mjs');
const workerCode = await fs.promises.readFile(workerPath, 'utf8');
const textLayerCSS = await fs.promises.readFile('src/foliate/text-layer.css', 'utf8');
const annotationLayerCSS = await fs.promises.readFile('src/foliate/annotation-layer.css', 'utf8');

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
  define: {
    '__TEXT_LAYER_CSS__': JSON.stringify(textLayerCSS),
    '__ANNOTATION_LAYER_CSS__': JSON.stringify(annotationLayerCSS),
    '__PDF_WORKER_CODE__': JSON.stringify(workerCode),
  },
  plugins: [
    {
      name: 'ignore-css',
      setup(build) {
        build.onResolve({ filter: /\.css$/ }, () => {
          return { path: 'css-stub', namespace: 'css-stub' };
        });
        build.onLoad({ filter: /.*/, namespace: 'css-stub' }, () => {
          return { contents: '', loader: 'text' };
        });
      },
    },
  ],
});

if (prod) {
  await buildStyles();
  await context.rebuild();
  process.exit(0);
} else {
  await buildStyles();
  await context.watch();
}
