import { defineConfig, type Plugin } from 'vite';
import builtins from 'builtin-modules';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/

if (!Map.prototype.getOrInsertComputed) {
    Map.prototype.getOrInsertComputed = function(key, computeFn) {
        if (this.has(key)) return this.get(key);
        var value = computeFn();
        this.set(key, value);
        return value;
    };
}
`;

function prepareFoliatePdf(): Plugin {
  const pdfDir = path.resolve(__dirname, 'node_modules/foliate-js/vendor/pdfjs');
  const workerCode = fs.readFileSync(path.join(pdfDir, 'pdf.worker.mjs'), 'utf8');
  const workerCodeBase64 = Buffer.from(workerCode).toString('base64');
  const textLayerBuilderCSS = fs.readFileSync(path.join(pdfDir, 'text_layer_builder.css'), 'utf8');
  const annotationLayerBuilderCSS = fs.readFileSync(path.join(pdfDir, 'annotation_layer_builder.css'), 'utf8');
  const lockfile = JSON.parse(fs.readFileSync(path.resolve(__dirname, 'package-lock.json'), 'utf8'));
  const foliateResolved = lockfile.packages?.['node_modules/foliate-js']?.resolved as string | undefined;
  const foliateRef = foliateResolved?.match(/#(.+)$/)?.[1] ?? 'main';
  const pdfAssetBase = `https://cdn.jsdelivr.net/gh/johnfactotum/foliate-js@${foliateRef}/vendor/pdfjs/`;

  return {
    name: 'prepare-foliate-pdf',
    transform(code, id) {
      if (!id.replace(/\\/g, '/').endsWith('/node_modules/foliate-js/pdf.js')) return;
      return code
        .replace(
          "const pdfjsPath = path => new URL(`vendor/pdfjs/${path}`, import.meta.url).toString()",
          `const pdfjsWorkerCode = atob(${JSON.stringify(workerCodeBase64)})\nconst pdfjsWorkerUrl = URL.createObjectURL(new Blob([pdfjsWorkerCode], { type: 'text/javascript' }))\nconst pdfjsPath = path => path === 'pdf.worker.mjs'\n    ? pdfjsWorkerUrl\n    : path === 'cmaps/'\n        ? '${pdfAssetBase}cmaps/'\n        : path === 'standard_fonts/'\n            ? '${pdfAssetBase}standard_fonts/'\n            : path`,
        )
        .replace(
          /const fetchText = async url => await \(await fetch\(url\)\)\.text\(\)\n\n\/\/ https:\/\/raw\.githubusercontent\.com\/mozilla\/pdf\.js\/refs\/tags\/v5\.5\.207\/web\/text_layer_builder\.css\nconst textLayerBuilderCSS = await fetchText\(pdfjsPath\('text_layer_builder\.css'\)\)\n\n\/\/ https:\/\/raw\.githubusercontent\.com\/mozilla\/pdf\.js\/refs\/tags\/v5\.5\.207\/web\/annotation_layer_builder\.css\nconst annotationLayerBuilderCSS = await fetchText\(pdfjsPath\('annotation_layer_builder\.css'\)\)/,
          `const textLayerBuilderCSS = ${JSON.stringify(textLayerBuilderCSS)}\nconst annotationLayerBuilderCSS = ${JSON.stringify(annotationLayerBuilderCSS)}`,
        );
    },
  };
}

// Plugin to ignore CSS imports from dependencies (we handle CSS separately)
function ignoreCSS(): Plugin {
  return {
    name: 'ignore-css',
    transform(_, id) {
      if (id.endsWith('.css')) return '';
    },
    resolveId(id) {
      if (id.endsWith('.css')) return { id: '\0css-stub', moduleSideEffects: false };
    },
    load(id) {
      if (id === '\0css-stub') return '';
    },
  };
}

// Build our standalone styles.css from src/global.css
// (Obsidian loads styles.css from plugin root, not via JS import)
function buildStylesPlugin(prod: boolean): Plugin {
  return {
    name: 'build-styles',
    apply: 'build',
    async closeBundle() {
      const css = await fs.promises.readFile('src/global.css', 'utf8');

      // Minify in production using the Vite-bundled esbuild
      const outputCss = prod
        ? (await import('vite').then((m) =>
            (m as any).transformWithEsbuild(css, 'styles.css', { minify: true, loader: 'css' }),
          )).code
        : css;

      // Write to both dist/ (Vite output dir) and plugin root
      await fs.promises.writeFile('dist/styles.css', outputCss);
      console.log('Written styles.css');
    },
  };
}

export default defineConfig(({ mode }) => {
  const prod = mode === 'production';

  return {
    plugins: [
      prepareFoliatePdf(),
      ignoreCSS(),
      buildStylesPlugin(prod),
    ],
    define: {
      'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
    },
    build: {
      lib: {
        entry: path.resolve(__dirname, 'src/main.ts'),
        formats: ['cjs'],
        fileName: () => 'main.js',
      },
      rollupOptions: {
        external: [
          'obsidian',
          'electron',
          '@codemirror/autocomplete',
          '@codemirror/collab',
          '@codemirror/commands',
          '@codemirror/language',
          '@codemirror/lint',
          '@codemirror/search',
          '@codemirror/state',
          '@codemirror/view',
          '@lezer/common',
          '@lezer/highlight',
          '@lezer/lr',
          ...builtins,
        ],
        output: {
          banner,
          entryFileNames: 'main.js',
          inlineDynamicImports: true,
        },
      },
      target: 'es2020',
      sourcemap: prod ? false : 'inline',
      minify: prod ? 'esbuild' : false,
      emptyOutDir: false,
      outDir: 'dist',
    },
  };
});
