import { defineConfig, type Plugin } from 'vite';
import builtins from 'builtin-modules';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/

// Polyfill for pdfjs-dist v5 which uses Map.prototype.getOrInsertComputed
if (!Map.prototype.getOrInsertComputed) {
    Map.prototype.getOrInsertComputed = function(key, computeFn) {
        if (this.has(key)) return this.get(key);
        var value = computeFn();
        this.set(key, value);
        return value;
    };
}
`;

// Read assets for PDF book adapter defines
const workerPath = require.resolve('pdfjs-dist/build/pdf.worker.min.mjs');
const workerCode = fs.readFileSync(workerPath, 'utf8');
// Plugin to ignore CSS imports from dependencies (we handle CSS separately)
function ignoreCSS(): Plugin {
  return {
    name: 'ignore-css',
    transform(_, id) {
      if (id.endsWith('.css')) return '';
    },
    resolveId(id) {
      if (id.endsWith('.css')) return { id: '\0css-stub', moduleSideEffects: false };
    },
    load(id) {
      if (id === '\0css-stub') return '';
    },
  };
}

// Build our standalone styles.css from src/global.css
// (Obsidian loads styles.css from plugin root, not via JS import)
function buildStylesPlugin(prod: boolean): Plugin {
  return {
    name: 'build-styles',
    apply: 'build',
    async closeBundle() {
      const css = await fs.promises.readFile('src/global.css', 'utf8');

      // Minify in production using the Vite-bundled esbuild
      const outputCss = prod
        ? (await import('vite').then((m) =>
            (m as any).transformWithEsbuild(css, 'styles.css', { minify: true, loader: 'css' }),
          )).code
        : css;

      // Write to both dist/ (Vite output dir) and plugin root
      await fs.promises.writeFile('dist/styles.css', outputCss);
      console.log('Written styles.css');
    },
  };
}

export default defineConfig(({ mode }) => {
  const prod = mode === 'production';

  return {
    plugins: [
      ignoreCSS(),
      buildStylesPlugin(prod),
    ],
    build: {
      lib: {
        entry: path.resolve(__dirname, 'src/main.ts'),
        formats: ['cjs'],
        fileName: () => 'main.js',
      },
      rollupOptions: {
        external: [
          'obsidian',
          'electron',
          '@codemirror/autocomplete',
          '@codemirror/collab',
          '@codemirror/commands',
          '@codemirror/language',
          '@codemirror/lint',
          '@codemirror/search',
          '@codemirror/state',
          '@codemirror/view',
          '@lezer/common',
          '@lezer/highlight',
          '@lezer/lr',
          ...builtins,
        ],
        output: {
          banner,
          entryFileNames: 'main.js',
          inlineDynamicImports: true,
        },
      },
      target: 'es2020',
      sourcemap: prod ? false : 'inline',
      minify: prod ? 'esbuild' : false,
      emptyOutDir: false,
      outDir: 'dist',
    },
    define: {
      '__PDF_WORKER_CODE__': JSON.stringify(workerCode),
    },
  };
});
